remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Site Settings
locale                   : "en"
title                    : "Teresa Arroyo Portfolio"
title_separator          : "-"
name                     : &name "Teresa Arroyo"
description              : &description "Teresa Arroyo Portfolio"
url                      : "https://teresaarroyo.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "teresaarroyo/teresaarroyo.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
search                   : false

# Social Sharing
#twitter:
#  username: &twitter "metalamin"
  
# Site Author  
author:
  name   : "Teresa arroyo"
  avatar : "/assets/bio-photo.jpg"
  bio    : "My name is Teresa and I'm a designer and cartoonist"
  location: "Madrid, Spain"
  email  : # optional
  uri    : "https://teresaarroyo.github.io"
  home   :
  github : "teresaarroyo"
  #twitter: *twitter

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
      

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
    
    
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-35351708-1"
